### PR TITLE
Add mock data factory

### PR DESCRIPTION
**Pull request by liu-ziyang**
Add mock data factory to allow user mocking data in plugin testing:

Users would be able to call mock_image(), mock_labels() etc directly to get a mock layer to work with

cc @neuromusic

### CODE REVIEW

**Review by sofroniewn — COMMENTED** [review]
Overall this seems ok - but I would have expected something named `Mock` to be more related to [unittest.mock](https://docs.python.org/3/library/unittest.mock.html#module-unittest.mock) where you can make assertions how individual methods are used, and we might want to provide something like that too.

I see what you've done as more about providing sample data and that it's a little bit closer to our [parameterized layer fixture](https://github.com/napari/napari/blob/447d7bfd1f604e75656a201259b0348e2e33fb00/napari/conftest.py#L163-L213) or our [layers fixture](https://github.com/napari/napari/blob/447d7bfd1f604e75656a201259b0348e2e33fb00/napari/conftest.py#L216-L233)

I might then write this a little bit more like that, as it's then easy to use with pytest. See how use a fixture like that to test some builtin plugin functionality works as expected https://github.com/napari/napari/blob/c5d10bc6f1806d82fead9a94e36cf9cf37f34a81/napari/plugins/_tests/test_save_layers.py#L35-L56. Needing the additional `mock_labels` calls seems like an extra level of indirection, but maybe I'm missing something on the use case and an example usage in this PR might help clarify that.

I can see the virtue of having an easy to use `viewer` though, particularly as we pass the viewer to the dock widget hook spook. Right now we pass the full `Viewer` (not just the `ViewerModel`) and so should probably use that here for now too for testing, but I could imagine one day a hookspec that only took the viewer model and then we'd use that too.

**Comment by tlambert03** [comment]
yeah, I agree with @sofroniewn, I like the idea, but I think the implementation needs some work.  I agree the word mock isn't quite right here, it's more like a fixture.  I'd also like to see a usage example... I suspect that the implicit viewer_model being used here is going to confuse people who may also try to use the `make_napari_viewer` fixture in the same test.  As such, this might be better suited as methods on our test_viewer fixture

```python
def test_something(make_napari_viewer):
	viewer = make_napari_viewer()
	image_layer = viewer.add_test_image()  # method on test viewer
```

as a side note here, as implemented here (something that merely instantiates a class and returns it) there's really no need for a pytest fixture at all.  Users could (and probably should) just instantiate `MockDataFactory()` directly.  But, as mentioned above, I'm not sure that's the API we should aim for here.

If you don't like the proposal above, let's discuss user API first (with usage examples), and then discuss how we should implement it.

**Comment by liu-ziyang** [comment]
I would love to have @neuromusic speak more on this. I will add my personal take for the intended use case:
We want to allow the users to initiate multiple different layers, while able to initialize with their own data when it only makes sense to test against specific image data to validate plugin function. For example, if a plugin needs a brain cell image to do segmentation work, the developer may want to feed their own data to create a layer to work with and test their plugin against it. Also, another use case is the ability to initiate multiple layers to check plugin function against different layers than multiple layers with the same dataset, and because of this mixture, I ended up providing the factory as the fixture, instead of the current approaches in napari that directly provides layers as the fixture.

Implementation wise, I agree that mock is somewhat confusing because, 1: right now it is not a mock layer, it actually uses the real viewer to create the layers, which happens to be my second point, that we are creating a viewer just to initialize the layers. Ideally, I would love to really mock them out so that the object is a data mock instead of the real one, but the risk of running off sync with napari outed the gain of having an independent mock. Now that we are dependent on napari anyway, it might be easier to go with this approach for now.

Happy to hear more about what you feel, I am totally happy to do some renaming to reduce the level of confusion as well. It was named mock data when I discussed this with Justin early, and now that the scope is slightly shifted, we can totally rename it to something else

**Comment by tlambert03** [comment]
> For example, if a plugin needs a brain cell image to do segmentation work, the developer may want to feed their own data to create a layer to work with and test their plugin against it. 

definitely... but why wouldn't they just use `viewer.add_image(their_own_data)`?  what are we providing here that helps that developer?

> Also, another use case is the ability to initiate multiple layers to check plugin function against different layers than multiple layers with the same dataset, and because of this mixture, I ended up providing the factory as the fixture, instead of the current approaches in napari that directly provides layers as the fixture.

not sure i'm following... why not just add some factory functions to the test viewer itself [as shown above](https://github.com/napari/napari-plugin-devtools/pull/13#issuecomment-801058463).  Basically, either the user _has_ some data, in which case they're going to just use `viewer.add_<layer>(my_data)` ... or they _don't_ have data, in which case they could use `viewer.add_test_<layer>` ... right?  If I'm missing a use case there, maybe show me some pseudocode that demonstrates it.

> we are creating a viewer just to initialize the layers.

yes, I wondered about that too... if you just want a layer without a viewer, why not just use the layer constructor directly?  using an internal viewer_model definitely has the possibility to confuse someone who has already created a test viewer with `make_test_viewer`.  

> I would love to really mock them out so that the object is a data mock instead of the real one

that's quite easy using unittest.mock.  I guess this is one of those cases where I'm wondering what value we're provided over already existing functionality in the standard library?  the main thing that I can see being useful here is the concept of "just add a random layer of X type" ... which could be done with `viewer.add_test_<layer>`.  but let me know if I'm still missing it

**Comment by sofroniewn** [comment]
All great discussion above - having some concrete use cases I think will help, but one thing that occurred to me is we could do

```python
	viewer = make_napari_viewer(test_image=...., test_labels=....)
```

As a convenience API. This could be one the napari side, and we'd have to decide if the additional API complexity is worth it compared to just creating the viewer then adding the layers. It's not quite clear what `...` is - is it a list of ndim/ shapes or could it be more complex stuff. We probably wouldn't want all the layer kwargs available.

Anyway that's just a thought, might be a bad idea.

> that's quite easy using unittest.mock. I guess this is one of those cases where I'm wondering what value we're provided over already existing functionality in the standard library? 

I think here the only convenience is that we've already done the mocking like this text for example https://github.com/napari/napari/blob/c5d10bc6f1806d82fead9a94e36cf9cf37f34a81/napari/_tests/test_view_layers.py#L149-L171 we could try and make easier to write, but if you aren't familiar with the API of MagicMock it'll still be hard to write that test.

> Ideally, I would love to really mock them out so that the object is a data mock instead of the real one, but the risk of running off sync with napari outed the gain of having an independent mock. Now that we are dependent on napari anyway, it might be easier to go with this approach for now.

I think there might also be a slight disconnect where @ziyangczi is thinking of mocking whole napari objects so we don't need to use them at all, where I think @tlambert03 and I are thinking of just mocking individual methods on napari objects so we know they are getting called with the right parameters for example, or returning the right results.

----------------

As noted above, having some concrete use cases here will help. Maybe let's think about the use case of an IO plugin developer who wants to know that their plugin returns layer data that can be loaded into napari or they want to know that their plugin can write napari data and we try and make that really easy.

For writing napari data we can look at napari-svg, see https://github.com/napari/napari-svg/blob/master/napari_svg/_tests/test_get_writer.py and https://github.com/napari/napari-svg/blob/master/napari_svg/_tests/test_write_layer.py. Here you can see I define my own layer fixtures, it would be nice if I could have important those from napari itself (maybe I already could).

For a reader plugin maybe we can get some inspiration from how we test some of our builtin readers https://github.com/napari/napari/blob/c5d10bc6f1806d82fead9a94e36cf9cf37f34a81/napari/plugins/_tests/test_reader_plugins.py

If we get the testing really nice for IO plugins we can then move on to the analysis / GUI ones, which might be a bit harder. For IO plugin the desired goal is much more clear. We could also provide something that could test a full round trip if there is both reader and writer.

Note that not all of this needs to be done now, and we could prioritize other needs first, but this is one option if we think about how to move forward

**Comment by tlambert03** [comment]
> viewer = make_napari_viewer(test_image=...., test_labels=....)

I have a strongly averse reaction to that one 😂 ... I can't see any benefit of adding a new API "just for testing" when we already have a canonical way to add data to a viewer.

> I think there might also be a slight disconnect where @ziyangczi is thinking of mocking whole napari objects so we don't need to use them at all, where I think @tlambert03 and I are thinking of just mocking individual methods on napari objects so we know they are getting called with the right parameters for example, or returning the right results.

perhaps... that's where a usage example would come in handy.  @ziyangczi, if you can show me an example (in code) of what a user can't currently do, but should be able to do, that would be super useful in this discussion.

**Comment by liu-ziyang** [comment]
> perhaps... that's where a usage example would come in handy. @ziyangczi, if you can show me an example (in code) of what a user can't currently do, but should be able to do, that would be super useful in this discussion.

technically there is nothing you "can't do", given that all of the code here can be copy and pasted to users' code and do the same thing, what we are trying to achieve here is 2 things:
1. remove the knowledge gap of understanding of layer level specifics setup, you can create a layer of your desired type with some random data without the understanding of what data is required, (though you still need to understand the data to bring your own data to set up the layer)
2. provide the functionality so that all users don't need to copy and paste this part when they need this functionality, this is part of @neuromusic's vision to simplify and provide this utility to plugin devs' test pipeline


I hope this helps explain at least why this PR, I am planning to drop the controvsial create_viewer part, and duplicate some of the functional calls to use layer ctor directluy

**Comment by tlambert03** [comment]
> you can create a layer of your desired type with some random data without the understanding of what data is required

agreed, the primary "new thing" here is a couple test layers that someone can use. Hence my [original proposal](https://github.com/napari/napari-plugin-devtools/pull/13#issuecomment-801058463)

**Comment by liu-ziyang** [comment]
thank you both for your feedback and nice discussion! let me know if the revised version looks better to you

**Comment by tlambert03** [comment]
> let me know if the revised version looks better to you

I'm still looking for a response to why we wouldn't just have this be a method on the test viewer.  `viewer.add_test_image`, `viewer.add_test_points`, etc...

**Comment by liu-ziyang** [comment]
> > let me know if the revised version looks better to you
> 
> I'm still looking for a response to why we wouldn't just have this be a method on the test viewer. `viewer.add_test_image`, `viewer.add_test_points`, etc...

I may have understood it wrong but I don't think user would be initializing a test viewer at all to do this, the tests are techincally within plugins, and not napari internal test. Though if we want to formalize that test pattern and tell people: "Hey if you want to test your plugin you should initialize a test viewer and attach your plugin to it", then I have no objection moving these functionality there. This does increases the level of dependency and nestness of plugin and napari, I would hope we can try to decrease the nesting gradually, and not introduce extra complications

**Comment by tlambert03** [comment]
> I may have understood it wrong but I don't think user would be initializing a test viewer at all to do this, the tests are techincally within plugins, and not napari internal test.

please provide an example in code of how you picture a developer using this

**Comment by liu-ziyang** [comment]
> please provide an example in code of how you picture a developer using this

previously when it was a fixture people could call it as an argument:
```
test_api(layer_factory):
    image_layer = layer_factory.create_image_layer()
    label_layer = layer_factory.create_laber_layer()
    generated_track_layer = plugin_api_call(image_layer, label_layer)
    assertEquals(expected, generated_track_layer.data)
```

without providing the layer_factory as a fixure then you can do:
```
test_api():
    layer_factory = LayerFactory(dimension=(4096, 4096, 4096))
    image_layer = layer_factory.create_image_layer()
    label_layer = layer_factory.create_laber_layer()
    generated_track_layer = plugin_api_call(image_layer, label_layer)
    assertEquals(expected, generated_track_layer.data)
```

**Comment by liu-ziyang** [comment]
using napari-svg as an example also: https://github.com/napari/napari-svg/blob/master/napari_svg/_tests/test_write_layer.py
we took care of the layer creation, which also nicely hides all layer creation behind the scene so plugin devs don't have to learn specifics of a layer, they can just access the data directly to test IO.

I think the only benefit really to introduce this to the test_viewer instead is the convenience to cover the case for dock_widget. which may actually require a separate flow to test since it is much more than mocking data

**Comment by neuromusic** [comment]
Thanks for the convo all... some of this has been covered, but to reiterate...

Key use case is very close to @sofroniewn 's walkthrough of napari-svg: an i/o plugin that seeks to support saving all layers (along with attributes) to HDF5 then reading them back out. 

Current example implementation of tests are here:
- https://github.com/yapic/napari-hdf5-labels-io/blob/master/napari_hdf5_labels_io/_tests/test_writer.py
- https://github.com/yapic/napari-hdf5-labels-io/blob/master/napari_hdf5_labels_io/_tests/test_reader.py

Goal is to support a plugin dev writing such tests on layers, not just numpy arrays. A plugin dev will need support for both unit tests (writing or reading individual layers with as little else initiated as possible) and integration tests (say, a round trip test for a viewer with a bunch of layers). As @ziyangczi & I had discussed it, it would be sufficient to let users define their own minimal data to read/write (rather than offering synthetic or saved data for them).

With use and feedback and time, my hope would be that we could expand to fixtures for other plugin-specific needs, like synthetic data that meets certain statistics or fixtures for standardized "real" data or fixtures that synthesize metadata (e.g. all permutations of axis labels), all with a similar API.

**Comment by neuromusic** [comment]
Also, if there are existing utilities (fixtures, mocks, creators, etc) in napari's test suite that address these use cases and are useful for plugin devs, that's awesome! In that case, I'd want to ensure that plugin devs (a) can find them, (b) know how to use them, and (c) know that they won't disappear. For most projects, test utilities aren't importable, don't generate API docs for and don't have the same guarantees of longevity that the public API does. A third party would be using these "at their own risk" if they can get to them at all.

**Comment by tlambert03** [comment]
> Key use case is an i/o plugin that seeks to support saving all layers (along with attributes) to HDF5 then reading them back out.

perfect, thanks.  Ok, in that case, i feel like a better service to developers would be to give them fake data in exactly the same format that their reader/writer plugins would receive it.  So, _not_ a layer, but rather a layer data tuple that matches the format that our hook specs describe.  Take for example the [`napari_get_writer` hook spec](https://napari.org/plugins/stable/hook_specifications.html#napari.plugins.hook_specifications.napari_get_writer).  There, a plugin developer is tasked with returning a function that "accepts the same path, and a list of tuples containing the data for each layer being saved in the form of `(Layer.data, Layer._get_state(), Layer._type_string)`. The writer function should return a list of strings (the actual filepath(s) that were written)."  So it seems that the best thing we could do in this case is not something like `factory.create_image_layer()`, but rather something that pumps out valid `(path, layer_data_tuple)` for them to test their function.

for instance, with the [hdf5 test](https://github.com/yapic/napari-hdf5-labels-io/blob/master/napari_hdf5_labels_io/_tests/test_writer.py) that you posted above, their `test_layer_writer` could be simplified with something like this `layer_data_tuple_factory`:

```python
def test_layer_writer(tmp_path , layer_data_tuple_factory):
    for out_path, data, meta, layer_type in layer_data_tuple_factory(path=str(tmp_path / 'test.h5'), n=10):
        out = layer_writer(out_path, data, meta, layer_type, sparse = True)
        assert out == out_path
        assert os.path.isfile(out_path)
```

even better would be to assert that their layer_writer was returning the appropriate format.
Also, while in that example, the dev directly used the pytest tmp_path fixture, that would be an excellent scenario for creating an mock temporary file, and asserting that the file has been touched somehow.  a really good pattern for that sort of thing is to _yield_ a fixture and then do some additional stuff after the test has run:

```python
@pytest.fixture
def out_path():

    # create NamedTemporaryFile or something
    destination = ....

    # yield it
    yield destination
    
    # then when their test is done, verify that something happened
    if not looks_correct(destination.read_bytes()):
        raise AssertionError
```

In any case, I think testing those secondary functions that get returned by hook implementations would be an awesome service... but that we should go directly for the signatures and types that we declare those functions should have.

**Comment by tlambert03** [comment]
forgot to mention... this might also be a great place to use something like [hypothesis](https://hypothesis.readthedocs.io/en/latest/) behind the scenes to allow the plugin developer to give us some reasonable bounds on the parameters of the data that they might expect (i.e. data types, dimensionality, etc...) and then generate a bunch of fake data that meets those bounds.  This should be optional of course, I agree that an intro dev should just be able to say "give me something that looks like a points... don't care anything more".

**Comment by tlambert03** [comment]
> Also, if there are existing utilities (fixtures, mocks, creators, etc) in napari's test suite that address these use cases and are useful for plugin devs, that's awesome!

another thought I've been having here is that the needs of devs testing plugins and the needs of napari testing napari are very often similar.  Whenever that happens, I think we should add these things to napari core, rather than devtools.  For example, a factory that yields valid `layer_data_tuples` would be extremely useful in testing napari directly, and would let us delete a lot of "bespoke" fixtures that one contributor or the other made just to test something.

**Comment by liu-ziyang** [comment]
yeah, I agree that the bounds are very loosely defined now, and the school of thoughts between "avoiding code duplication" and "isolating access to the core components" may be in direct conflict. We may have to iteratively experiment with what component should we expose to the outer world so that people get what they need, without having to lose all control over the implementation details of internal components.

I am going to merge this PR for now, and we can continue thinking about this and move things around as necessary.

**Comment by tlambert03** [comment]
wait what?  did we decide we like this?

**Comment by liu-ziyang** [comment]
> wait what? did we decide we like this?

unless we are able to figure out the exact format of data tuples we want to expose, isn't the whole layer the best solution for now? I am not confident we can come up with a finite set of things that are useful to plugin devs.

as the example you pointed out above:
> ```def test_layer_writer(tmp_path , layer_data_tuple_factory):
>    for out_path, data, meta, layer_type in layer_data_tuple_factory(path=str(tmp_path / 'test.h5'), n=10):
>        out = layer_writer(out_path, data, meta, layer_type, sparse = True)
>        assert out == out_path
>        assert os.path.isfile(out_path)```

this requires feedback on the developer side and may need extra time to mature that we will be settling on `out_path, data, meta, layer_type`. Unless you are saying "no we don't want to provide anything until we figured out this", I don't see the suggested approach can be adapted immediately

**Comment by tlambert03** [comment]
I guess my main question is what opposition do you have to this proposal of mine:

>  I think testing those secondary functions that get returned by hook implementations would be an awesome service... but that we should go directly for the signatures and types that we declare those functions should have.

**Comment by sofroniewn** [comment]
> I am going to merge this PR for now, and we can continue thinking about this and move things around as necessary.

Let's hold on merge until we know that this is something we want to add here. Maybe we have a deep dive meeting next week to discuss more

**Comment by liu-ziyang** [comment]
> I guess my main question is what opposition do you have to this proposal of mine:
> 
> > I think testing those secondary functions that get returned by hook implementations would be an awesome service... but that we should go directly for the signatures and types that we declare those functions should have.

Now I am so very confused, I don't see why is my proposal is in opposition to yours. the signatures and types for these secondary functions should all be contained in the layers, then giving people the layer to work with is sufficient and necessary because this is the minimal way to expose all metadata within a layer that might be useful to plugin developers. Is there anything of a layer object that we want to keep internal so that we do not want to expose them to the plugin developer? If we are to create separate functions that returns different format of data tuples within the layer, I would then ask why not just return the layer directly and allow people to look at what's in there?

**Comment by liu-ziyang** [comment]
If this makes people feel more comfortable: we can change the return format of these factory methods to 
```
# layer data may be: (data,) (data, meta), or (data, meta, layer_type)
# using "Any" for the data type until ArrayLike is more mature.
FullLayerData = Tuple[Any, Dict, str]
```
instead of the layer itself, I don't want to go too specific and tie the factory method to each plugin specification immediately, at least not before we finalize everything and comfortable to remove the experimental tags from all our specs

**Comment by neuromusic** [comment]
> I don't want to go too specific and tie the factory method to each plugin specification immediately

This makes sense to me. If we have additional fixtures that are specifically for certain hook implementations, that's great, but there should be a layer fixture that can be used for any plugin that needs to interact with layers, not exclusively the i/o plugins in the above examples.

**Comment by liu-ziyang** [comment]
going to part the discussion and revisit the scope later

**Pull request closed without merging**
